# messaging_app/.github/workflows/dep.yml

name: Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        cd messaging_app
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest
