#!/bin/bash

echo "Deploying Blue and Green..."
kubectl apply -f messaging_app/blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml
kubectl apply -f messaging_app/kubeservice.yaml

echo "Logs for green deployment:"
kubectl logs -l version=green
